language: node_js

node_js:
- "lts/*"

branches:
  only:
  - master
install:
- npm install
script:
- npm run build

deploy:
  - provider: script
    skip-cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
