name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install
        run: npm
      - name: build
        run: npm run build
      - name: deploy
        run: sh scripts/deploy.sh
        env:
          CODINGNET_TOKEN: ${{ secrets.CODINGNET_TOKEN }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
