name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: sh scripts/deploy.sh
        env:
          CODINGNET_USERNAME: ${{ secrets.CODINGNET_USERNAME }}
          CODINGNET_TOKEN: ${{ secrets.CODINGNET_TOKEN }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
